import = ["/home/alex/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "SFMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Medium"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 14
y = 10
